apiVersion: v2
type: application
name: zipkin
home: https://zipkin.io
description: |-
  Zipkin is a distributed tracing system. It helps gather timing
  data needed to troubleshoot latency problems in service architectures.
  Features include both the collection and lookup of this data.
icon: https://zipkin.io/public/img/logo_png/zipkin_vertical_grey_gb.png
version: 0.2.0
appVersion: 2.21.0
keywords:
  - tracing
  - observability
  - open-source
  - opentracing
  - zipkin
sources:
  - https://github.com/openzipkin/zipkin/
  - https://github.com/carlosjgp/zipkin-chart
  - https://github.com/carlosjgp/open-charts
maintainers:
  - name: Carlos Juan Gómez Peñalver
    email: carlosjuangp@gmail.com
    url: https://github.com/carlosjgp
